<?php
/**
 * @file
 * Code for the Pro 101 Home Feature feature.
 */

include_once 'pro_101_home_feature.features.inc';

function pro_101_home_feature_views_slideshow_skin_info() {
  return array(
    'skinname' => array(
      'name' => t('Thumbnail Pager'),
      'class' => 'thumbnail-pager',
//    'module' => 'module_name',
//    'path' => 'skins',
//    'stylesheets' => array('file.css')
    )
  );
}
