<?php
/**
 * @file
 * pro_101_home_feature.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function pro_101_home_feature_views_default_views() {
  $export = array();

  $view = new view;
  $view->name = 'showcase';
  $view->description = 'Showcase featured content in a block.';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Showcase';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['query_comment'] = FALSE;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '3';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['expose']['items_per_page_options_all'] = 0;
  $handler->display->display_options['style_plugin'] = 'slideshow';
  $handler->display->display_options['style_options']['flexslider_views_slideshow']['optionset'] = 'front_page_showcase';
  $handler->display->display_options['style_options']['flexslider_views_slideshow']['caption_field'] = 'body';
  $handler->display->display_options['style_options']['slideshow_type'] = 'flexslider_views_slideshow';
  $handler->display->display_options['style_options']['slideshow_skin'] = 'default';
  $handler->display->display_options['style_options']['skin_info'] = array(
    'class' => 'default',
    'name' => 'Default',
    'module' => 'views_slideshow',
    'path' => '',
    'stylesheets' => array(),
  );
  $handler->display->display_options['style_options']['widgets']['top']['views_slideshow_pager']['weight'] = '1';
  $handler->display->display_options['style_options']['widgets']['top']['views_slideshow_controls']['weight'] = '1';
  $handler->display->display_options['style_options']['widgets']['top']['views_slideshow_controls']['type'] = 'views_slideshow_controls_text';
  $handler->display->display_options['style_options']['widgets']['top']['views_slideshow_slide_counter']['weight'] = '1';
  $handler->display->display_options['style_options']['widgets']['bottom']['views_slideshow_pager']['weight'] = '1';
  $handler->display->display_options['style_options']['widgets']['bottom']['views_slideshow_controls']['weight'] = '1';
  $handler->display->display_options['style_options']['widgets']['bottom']['views_slideshow_controls']['type'] = 'views_slideshow_controls_text';
  $handler->display->display_options['style_options']['widgets']['bottom']['views_slideshow_slide_counter']['weight'] = '1';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['timeout'] = '5000';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['speed'] = '700';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['delay'] = '0';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['start_paused'] = 0;
  $handler->display->display_options['style_options']['views_slideshow_cycle']['remember_slide_days'] = '1';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['items_per_slide'] = '1';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['wait_for_image_load_timeout'] = '3000';
  $handler->display->display_options['style_options']['views_slideshow_cycle']['cleartype'] = 0;
  $handler->display->display_options['style_options']['views_slideshow_cycle']['cleartypenobg'] = 0;
  $handler->display->display_options['row_plugin'] = 'ds';
  $handler->display->display_options['row_options']['alternating'] = 0;
  $handler->display->display_options['row_options']['grouping'] = 0;
  $handler->display->display_options['row_options']['advanced'] = 0;
  $handler->display->display_options['row_options']['delta_fieldset']['delta_fields'] = array();
  $handler->display->display_options['row_options']['grouping_fieldset']['group_field'] = 'node|created';
  $handler->display->display_options['row_options']['default_fieldset']['view_mode'] = 'teaser';
  /* Field: Content: Office Image */
  $handler->display->display_options['fields']['field_title_graphic']['id'] = 'field_title_graphic';
  $handler->display->display_options['fields']['field_title_graphic']['table'] = 'field_data_field_title_graphic';
  $handler->display->display_options['fields']['field_title_graphic']['field'] = 'field_title_graphic';
  $handler->display->display_options['fields']['field_title_graphic']['label'] = '';
  $handler->display->display_options['fields']['field_title_graphic']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['external'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['alter']['html'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_title_graphic']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['field_title_graphic']['hide_empty'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['empty_zero'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['field_title_graphic']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_title_graphic']['type'] = 'cs_adaptive_image';
  $handler->display->display_options['fields']['field_title_graphic']['settings'] = array(
    'relationship' => 'none',
    'ui_name' => 'Image',
    'custom_label' => 0,
    'label' => '',
    'element_label_colon' => 0,
    'exclude' => 0,
    'element_type_enable' => 0,
    'element_type' => '',
    'element_class_enable' => 0,
    'element_class' => '',
    'element_label_type_enable' => 0,
    'element_label_type' => '',
    'element_label_class_enable' => 0,
    'element_label_class' => '',
    'element_wrapper_type_enable' => 0,
    'element_wrapper_type' => '',
    'element_wrapper_class_enable' => 0,
    'element_wrapper_class' => '',
    'element_default_classes' => 1,
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'absolute' => 0,
      'replace_spaces' => 0,
      'external' => 0,
      'path_case' => 'none',
      'link_class' => '',
      'alt' => '',
      'rel' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'more_link' => 0,
      'more_link_text' => '',
      'more_link_path' => '',
      'html' => 0,
      'strip_tags' => 0,
      'preserve_tags' => '',
      'trim_whitespace' => 0,
      'nl2br' => 0,
    ),
    'empty' => '',
    'empty_zero' => 0,
    'hide_empty' => 0,
    'hide_alter_empty' => 1,
    'click_sort_column' => 'fid',
    'type' => 'cs_adaptive_image',
    'field_api_classes' => 0,
    'image_link' => 'content',
    'styles' => array(
      'breakpoint_1' => '740',
      'style_1' => 'thumbnail',
      'breakpoint_2' => '980',
      'style_2' => 'flexslider_full',
      'max_style' => 'flexslider_full',
      'fallback_style' => 'medium',
    ),
  );
  $handler->display->display_options['fields']['field_title_graphic']['group_rows'] = 1;
  $handler->display->display_options['fields']['field_title_graphic']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_title_graphic']['delta_reversed'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['delta_first_last'] = 0;
  $handler->display->display_options['fields']['field_title_graphic']['field_api_classes'] = 0;
  /* Field: Caption */
  $handler->display->display_options['fields']['body']['id'] = 'body';
  $handler->display->display_options['fields']['body']['table'] = 'field_data_body';
  $handler->display->display_options['fields']['body']['field'] = 'body';
  $handler->display->display_options['fields']['body']['ui_name'] = 'Caption';
  $handler->display->display_options['fields']['body']['label'] = '';
  $handler->display->display_options['fields']['body']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['body']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['body']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['body']['alter']['external'] = 0;
  $handler->display->display_options['fields']['body']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['body']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['body']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['body']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['body']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['body']['alter']['more_link'] = 0;
  $handler->display->display_options['fields']['body']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['body']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['body']['alter']['html'] = 0;
  $handler->display->display_options['fields']['body']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['body']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['body']['hide_empty'] = 0;
  $handler->display->display_options['fields']['body']['empty_zero'] = 0;
  $handler->display->display_options['fields']['body']['hide_alter_empty'] = 1;
  $handler->display->display_options['fields']['body']['field_api_classes'] = 0;
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'featured' => 'featured',
  );

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block');
  $export['showcase'] = $view;

  return $export;
}
